apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imo-api
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: imo-system            # <-- was argocd; set to imo-system
  source:
    repoURL: https://github.com/PranathiNanduri/imo-manifests.git
    targetRevision: main
    path: apps/imo-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true         # <-- let Argo create the namespace
