apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-crds
  namespace: argocd
  annotations:
    # Ensure CRDs are applied before the main monitoring chart
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-operator-crds
    # Argo requires a targetRevision for Helm charts.
    # Use a semver constraint so you don't have to hard-pin a specific version.
    # (Argo supports semver ranges for Helm charts.)
    targetRevision: '>=0.0.0'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
